# Generated by Django 4.2.7 on 2023-11-27 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(choices=[('*', '*'), ('* *', '* *'), ('* * *', '* * *'), ('* * * *', '* * * *'), ('* * * * *', '* * * * *')], max_length=10)),
                ('description', models.TextField()),
                ('film_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_list', to='main_page.filmlistmodel')),
            ],
        ),
    ]
